# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

#################################################################################################
# include paths to all our applications
includes:
# first include the configuration's global settings for application paths
- ./paths.yml

# now include overrides - these will be loaded if they are found
- sequences/{Sequence}/{Shot}/sgtk_overrides.yml
- assets/{sg_asset_type}/{Asset}/sgtk_overrides.yml


################################################################################################
# app definitions for all the Sgtk app launchers.

#
# -------------------------------------------------
# 3dsmax
# -------------------------------------------------
launch_3dsmax:
  defer_keyword: ''
  engine: tk-3dsmaxplus
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: ''
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: ''
  menu_name: Launch 3dsmax {version} # note: desktop app means we cannot have spaces in app name
  versions: ['2016','2017','2015']
  windows_args: ''
  windows_path: '@3dsmax_windows'
#
# -------------------------------------------------
# Hiero
# -------------------------------------------------
launch_hiero:
  defer_keyword: ''
  engine: tk-hiero
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_hiero_256.png'
  linux_args: --hiero
  linux_path: '@hiero_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@hiero_mac'
  menu_name: Launch Hiero {version}
  versions: [(9.0)v(8), (10.0)v(3)]
  windows_args: --hiero
  windows_path: '@hiero_win'
#
# -------------------------------------------------
# Houdini
# -------------------------------------------------
launch_houdini:
  defer_keyword: ''
  engine: tk-houdini
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: '@houdini_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@houdini_mac'
  menu_name: Launch Houdini {version}
  versions: ['15.0.244.16']
  windows_args: ''
  windows_path: '@houdini_windows'
#
# -------------------------------------------------
# Mari
# -------------------------------------------------
launch_mari:
  defer_keyword: ''
  engine: tk-mari
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: '@mari_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@mari_mac'
  menu_name: Launch Mari {version}
  versions: ['3.0v2']
  windows_args: ''
  windows_path: '@mari_windows'
#
# -------------------------------------------------
# Maya
# -------------------------------------------------
launch_maya:
  defer_keyword: ''
  engine: tk-maya
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: '@maya_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@maya_mac'
  menu_name: Launch Maya {version}
  versions: ['2016','2015']
  windows_args: ''
  windows_path: '@maya_windows'
#
# -------------------------------------------------
# Motionbuilder
# -------------------------------------------------
launch_motionbuilder:
  defer_keyword: ''
  engine: tk-motionbuilder
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: ''
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: ''
  menu_name: Launch MotionBuilder {version}
  versions: ['2016','2015','2014']
  windows_args: ''
  windows_path: '@motionbuilder_windows'
#
# -------------------------------------------------
# Nuke
# -------------------------------------------------
launch_nuke:
  defer_keyword: ''
  engine: tk-nuke
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: '@nuke_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@nuke_mac'
  menu_name: Launch Nuke {version}
  versions: [(9.0)v(8), (10.0)v(3)]
  windows_args: ''
  windows_path: '@nuke_windows'
#
# -------------------------------------------------
# NukeX
# -------------------------------------------------
launch_nukex:
  defer_keyword: ''
  engine: tk-nuke
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/NukeXApp.png'
  linux_args: ''
  linux_path: '@nuke_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@nuke_mac'
  menu_name: NukeX {version}
  versions: [(9.0)v(8), (10.0)v(3)]
  windows_args: --nukex
  windows_path: '@nuke_windows'
#
# -------------------------------------------------
# Nuke Studio
# -------------------------------------------------
launch_nukestudio:
  defer_keyword: ''
  engine: tk-nukestudio
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_nukestudio_256.png'
  linux_args: --studio
  linux_path: '@nukestudio_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@nukestudio_mac'
  menu_name: Launch NukeStudio {version}
  versions: [(9.0)v(8), (10.0)v(3)]
  windows_args: --studio
  windows_path: '@nukestudio_windows'
#
# -------------------------------------------------
# Photoshop CC
# -------------------------------------------------
launch_photoshopcc:
  defer_keyword: ''
  engine: tk-photoshopcc
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: ''
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: '@photoshop_mac'
  menu_name: Launch Photoshop {version}
  versions: ['2017','2016','2015','CS6']
  windows_args: ''
  windows_path: '@photoshop_win'
#
# -------------------------------------------------
# Screening Room
# -------------------------------------------------
launch_screeningroom:
  enable_rv_mode: true
  enable_web_mode: true
  location:
    version: v0.3.2
    type: app_store
    name: tk-multi-screeningroom
  rv_path_linux: '@rv_linux'
  rv_path_mac: '@rv_mac'
  rv_path_windows: '@rv_win'
  init_hook: '{self}/init.py'
#
# -------------------------------------------------
# Softimage
# -------------------------------------------------
launch_softimage:
  defer_keyword: ''
  engine: tk-softimage
  extra: {}
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: '@softimage_linux'
  location:
    version: v0.8.2
    type: app_store
    name: tk-multi-launchapp
  mac_args: ''
  mac_path: ''
  menu_name: Launch Softimage {version}
  versions: ['2013']
  windows_args: ''
  windows_path: '@softimage_windows'
#
# -------------------------------------------------
# Syntheyes
# -------------------------------------------------
launch_syntheyes:
  defer_keyword: ''
  engine: tk-syntheyes
  extra: '@syntheyes_extras'
  hook_app_launch: default
  hook_before_app_launch: default
  icon: '{target_engine}/icon_256.png'
  linux_args: ''
  linux_path: '@syntheyes_linux'
  location: {name: tk-multi-launchapp, type: dev, version: v0.6.4, path: 'C:\dev\sgtk\tk-multi-launchapp-0.6.4'}
  mac_args: ''
  mac_path: '@syntheyes_mac'
  menu_name: Launch SynthEyes
  versions: []
  windows_args: ''
  windows_path: '@syntheyes_windows'