# Copyright (c) 2015 Shotgun Software Inc.
#
# CONFIDENTIAL AND PROPRIETARY
#
# This work is provided "AS IS" and subject to the Shotgun Pipeline Toolkit
# Source Code License included in this distribution package. See LICENSE.
# By accessing, using, copying or modifying this work you indicate your
# agreement to the Shotgun Pipeline Toolkit Source Code License. All rights
# not expressly granted therein are reserved by Shotgun Software Inc.
#

#
# This file defines paths to key applications for the project
#

#
# Mari
#
mari_linux: 'Mari3.0'
mari_mac: /Applications/Mari3.0v2
mari_windows: 'C:\Program Files\Mari{version}\Bundle\bin\Mari{version}.exe'


#
# Maya
#
maya_windows: 'C:\Program Files\Autodesk\Maya{version}\bin\maya.exe'
maya_mac: /Applications/Autodesk/maya{version}/Maya.app
maya_linux: maya


#
# Nuke
#
nuke_mac: /Applications/Nuke{version}/Nuke{version}.app
nuke_windows: 'Z:/halon/sys/windows/share/apps/nuke/{v0}.{v1}/Nuke{v0}.exe'
# LocalNuke: 
# nuke_windows: 'C:\Program Files\Nuke{version}\Nuke{v0}.exe'
nuke_linux: Nuke{v0}


#
# Nuke Studio
#
nukestudio_mac: /Applications/Nuke{version}/NukeStudio{version}.app
nukestudio_windows: 'C:\Program Files\Nuke{version}\Nuke{v0}.exe'
nukestudio_linux: Nuke{v0}


#
# motionbuilder
#
motionbuilder_windows: 'C:\Program Files\Autodesk\MotionBuilder {version}\bin\x64\motionbuilder.exe'


#
# 3dsmax 2015
#
3dsmax_windows: 'C:\Program Files\Autodesk\3ds Max {version}\3dsmax.exe'


#
# Houdini
#
houdini_mac: /Applications/Houdini {version}/Houdini.app
houdini_windows: 'C:\Program Files\Side Effects Software\Houdini {version}\bin\houdini.exe'
houdini_linux: '/opt/hfs15.0.244.16/bin/houdini'


#
# Photoshop CC
#
photoshop_mac: /Applications/Adobe Photoshop CC {version}/Adobe Photoshop CC {version}.app
photoshop_win: 'C:\Program Files\Adobe\Adobe Photoshop CC {version}\Photoshop.exe'


#
# Hiero
#
hiero_mac: /Applications/Nuke{version}/Hiero{version}.app
hiero_win: 'C:\Program Files\Nuke{version}\Nuke{v0}.exe'
hiero_linux: Nuke9.0


#
# Softimage
#
softimage_windows: C:\Program Files\Autodesk\Softimage {version}\Application\bin\XSI.bat
softimage_linux: XSI

#
# Syntheyes
#
syntheyes_mac: /Applications/SynthEyes/SynthEyes.app
syntheyes_windows: 'Z:\halon\sys\windows\share\apps\syntheyes\1702.1039\SynthEyes64.exe'
#syntheyes_windows: 'C:\Program Files\Andersson Technologies LLC\SynthEyes\SynthEyes64.exe'
syntheyes_linux: SynthEyes
syntheyes_extras:         
    mac_python_path: /usr/bin/python
    linux_python_path: python
    windows_python_path: 'Z:\halon\sys\windows\share\apps\python\2.7\pythonw.exe'
    extreme: ''

#
# Tweak RV
#
rv_mac: /Applications/RV64.app
rv_win: Z:\halon\sys\windows\share\apps\rv\7.1.1\bin\rv.exe
rv_linux: rv
